# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

[GLOBAL]
pants_version = "2.0.0"
pantsd = true  # Enable the Pants daemon for better performance.
build_patterns = ["BUILD", "BUILD.pants"]

backend_packages.add = [
  'pants.backend.python',
  'pants.backend.python.typecheck.mypy',
  'pants.backend.python.lint.flake8',
  'pants.backend.python.lint.pylint',
  'pants.backend.python.lint.bandit',
  'pants.backend.python.lint.docformatter',
  'pants.backend.python.lint.isort',
]

[source]
marker_filenames = ['setup.py']

[python-setup]
interpreter_constraints = [">=3.7"]
requirement_constraints = "3rdparty/constraints.txt"

[mypy]
config = ".build-support/mypy.ini"

[flake8]
config = ".build-support/.flake8"

[pylint]
config = ".build-support/.pylintrc"

[bandit]
config = ".build-support/.bandit.yml"
