trigger:
  branches:
    include:
      - master
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: pip_install
    displayName: 'pip install deps'

    jobs:
      - job: 'python'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.8'

          - script: pip install -r dev_requirements.txt
            displayName: 'Install python dependencies'

          - script: python -m flake8 . --config=.flake8
            displayName: 'Run flake8'

          - script: python -m pylint .
            displayName: 'Run pylint'

          - script: python -m bandit -r .
            displayName: 'Run bandit'
