trigger:
  branches:
    include:
      - master
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: pip_install
    displayName: 'pip install deps'

    jobs:
      - job: 'python'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.8'

          - script: which python
          - script: which pip
          - script: which conda

          - script: pip install -r dev_requirements.txt
            displayName: 'Install python dependencies'

          - script: flake8 . --config=.ini-files/.flake8
            displayName: 'Run flake8'

          - script: mypy app_iqor/ lib_py_utils/py_utils/ --config-file .ini-files/mypy.ini
            displayName: 'Run mypy'

          - script: bandit -r . --configfile .ini-files/.bandit.yml
            displayName: 'Run bandit'

          - script: pylint app_iqor/ lib_py_utils/py_utils/  --rcfile=.ini-files/.pylintrc
            displayName: 'Run pylint'
