trigger:
  branches:
    include:
      - master
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  PY_VERSION: 3.8
  PY_ENV_PATH: $(Pipeline.Workspace)/.env

stages:
  - stage: pip_install
    displayName: 'pip install deps'

    jobs:
      - job: 'python'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(PY_VERSION)'
          - bash: |
              PIP="pip install -r dev_requirements.txt --target $(PY_ENV_PATH)" 
              echo $PIP
              eval $PIP
  
              SET_PYTHONPATH="export PYTHONPATH=$(PY_ENV_PATH)"
              echo $SET_PYTHONPATH
              eval $SET_PYTHONPATH
              echo "Set PYTHONPATH to:"
              echo $PYTHONPATH

              SET_PATH="export PATH=$(PY_ENV_PATH)/bin:$PATH"
              echo $PATH
              which pip
              which python
              which mypy
            displayName: pip install
