trigger:
  branches:
    include:
      - master
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  PY_VERSION: 3.8
  PY_ENV_PATH: $(Pipeline.Workspace)/.env
  REINSTALL_DEPS: 'false'

stages:
  - stage: install_deps
    displayName: 'install deps'

  - stage: lint
    displayName: 'lint'
    jobs:
      - job: lint_py
        steps:
          - template: use_py_deps.yml
          - script: |
              which mypy
              which flake8
              which bandit
              which pylint
            displayName: Sanity check py linters

          - script: flake8 . --config=.ini-files/.flake8
            displayName: 'Run flake8'

          - script: mypy app_iqor/ lib_py_utils/py_utils/ --config-file .ini-files/mypy.ini
            displayName: 'Run mypy'

          - script: bandit -r . --configfile .ini-files/.bandit.yml
            displayName: 'Run bandit'

          - script: pylint app_iqor/ lib_py_utils/py_utils/  --rcfile=.ini-files/.pylintrc
            displayName: 'Run pylint'