stages:
- stage: lint
  displayName: 'Lint'

  jobs:
    - job: 'flake8'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.8'
        - script: flake8 . --config=.flake8
          displayName: 'Run flake8'
  
    - job: 'pylint'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.8'
        - script: pylint .
          displayName: 'Run pylint'
  
    - job: 'bandit'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.8'
        - script: bandit -r .
          displayName: 'Run bandit'
