trigger:
  branches:
    include:
      - '*'

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  PY_VERSION: 3.8
  PY_ENV_PATH: $(Pipeline.Workspace)/.env
  NODE_INSTALL_PATH: $(Pipeline.Workspace)/.node_home
  REINSTALL_DEPS: true

stages:
  - stage: install_deps
    displayName: 'install deps'
    jobs:
      - job: install_python_deps
        steps:
          - template: ../templates/setup_py.yml
          - script: |
              PIP="python -m pip install --upgrade \
                   -c 3rdparty/py-env-ws/constraints.txt \
                   -r 3rdparty/py-env-ws/requirements.txt \
                   -r 3rdparty/py-env-ws/dev-requirements.txt \
                   -r 3rdparty/py-env-ws/mypy-requirements.txt \
                   -r 3rdparty/py-env-ws/nb-requirements.txt \
                   --target $(PY_ENV_PATH)"
              echo "> $PIP"
              eval $PIP
            displayName: pip install
            condition: or(eq(variables.CONDA_CACHE_RESTORED, 'false'), eq(variables.REINSTALL_DEPS, 'true'))

  - stage: lint
    displayName: 'lint'
    dependsOn: install_deps
    jobs:
      - job: lint_py
        steps:
          - template: ../templates/use_py_deps.yml
          - script: |
              which python
              which mypy
              which flake8
              which bandit
              which pylint
              which isort
              which docformatter
              which flynt
            displayName: 'Sanity check py tools'
          - script: make lint-py
            displayName: 'Type check and lint py'
      - job: lint_hs
        steps:
          - script: curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s tutorials_hs/
            displayName: 'Run hlint'
      - job: lint_sh
        steps:
          - script: make lint-sh
            displayName: 'Run shellcheck'
      - job: lint_yaml
        steps:
          - template: ../templates/use_py_deps.yml
          - script: make lint-yml
            displayName: 'Run yamllint'
      - job: lint_markdown
        steps:
          - script: make -j1 env-md lint-md
            displayName: 'Run markdownlint'

  - stage: test_py
    dependsOn: install_deps
    displayName: 'test py'
    jobs:
      - job: test_py
        steps:
          - template: ../templates/use_py_deps.yml
          - script: |
              which pytest
            displayName: 'Sanity check pytest'

          - script: make test-py
            displayName: 'Test py'

  - stage: test_sh
    dependsOn: [ ]
    displayName: 'test sh'
    jobs:
      - job: test_sh
        steps:
          - script: |
              wget https://nodejs.org/dist/v16.3.0/node-v16.3.0-linux-x64.tar.xz
              mkdir -p $(NODE_INSTALL_PATH)
              tar -xvf node-v16.3.0-linux-x64.tar.xz --directory $(NODE_INSTALL_PATH)
              echo "##vso[task.prependpath]$(NODE_INSTALL_PATH)/node-v16.3.0-linux-x64/bin"
            displayName: 'Download, untar and append npm to path'
          - script: |
              command -v npm
              make -j1 env-sh test-sh
            displayName: 'Test sh'
