from pathlib import Path

from setuptools import setup

LIB_ROOT = Path(__file__).parent
REQS_FILE = LIB_ROOT / 'autogenerated-requirements.txt'


def main() -> None:
    setup(
        name='py_utils',
        version='0.1',
        packages=['py_utils'],
        python_requires='>=3.8',
        install_requires=REQS_FILE.read_text(),
        zip_safe=False,  # for mypy
        package_data={'py_utils': ['py.typed']},  # expose types to users
        author='Cristian Matache',
        author_email='cm@example.com',
        description='',
        long_description='',
    )


if __name__ == '__main__':
    main()
